# Generated by Django 2.1 on 2019-07-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.TextField(null=True)),
                ('name', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
