# Generated by Django 2.1 on 2019-07-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='email_id',
        ),
        migrations.AddField(
            model_name='registration',
            name='lastname',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='mobile',
            field=models.BigIntegerField(null=True),
        ),
    ]
